### PR TITLE
Add recipe for origami.

### PR DESCRIPTION
**Pull request by jcs090218**
I saw your email! This is the fork of the original origami package. And celpa idead is very cool! Thanks for the hard work! 😄

### CODE REVIEW

**Comment by conao3** [comment]
Good! But it has the same name and version number, I'm not sure how PACKAGE would interpret it.
You need to add the constants in the version number to make the package interpret that it is newer than MELPA.

**Comment by conao3** [comment]
How about collaborator? Would you join?

**Comment by jcs090218** [comment]
@conao3 I would like to join yet not sure how much time I could put into this project though! If you don't mind, my answer is yes! :)

**Comment by conao3** [comment]
Good! I send the invitation.

**Comment by jcs090218** [comment]
Joined! Let me know if you need any help! :)

And thanks again! 😄

**Comment by conao3** [comment]
Yes! OK!
(FYI: build failed about your fork origami https://github.com/conao3/celpa/runs/675040558?check_suite_focus=true#step:7:28
I investigate why)

**Comment by conao3** [comment]
Missing repository at https://github.com/jcs-elpa/origami ...?

**Comment by jcs090218** [comment]
See #3

**Pull request merged**
