### PR TITLE
Fixed missing repo when build.

### PR DESCRIPTION
**Pull request by jcs090218**
Sorry for not paying attention, is a bit late here.

### CODE REVIEW

**Comment by jcs090218** [comment]
Sorry for the wrong naming, it name it the way that I don't normally named. (By adding `.el` at the back of the repository's name.) :P

**Comment by conao3** [comment]
Don't worry, And we improve CI by the way :)

**Comment by conao3** [comment]
Now all resources are 403. Please wait for a moment...

**Comment by conao3** [comment]
Now everything good!

**Comment by conao3** [comment]
Our archive should be most latest than MELPA via [this commit](https://github.com/conao3/celpa/commit/d616368aab97f67109a105e21cbaa0c8c5eb81a2)

**Pull request merged**
